/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package analisador_lexico;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PUBLIC = 1;
  /** RegularExpression Id. */
  int CLASS = 2;
  /** RegularExpression Id. */
  int STATIC = 3;
  /** RegularExpression Id. */
  int VOID = 4;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int RETURN = 6;
  /** RegularExpression Id. */
  int EXTENDS = 7;
  /** RegularExpression Id. */
  int NEW = 8;
  /** RegularExpression Id. */
  int PRINT = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int LENGTH = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int THIS = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int INTEGER = 22;
  /** RegularExpression Id. */
  int REAL = 23;
  /** RegularExpression Id. */
  int IDENTIFIER = 24;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 25;
  /** RegularExpression Id. */
  int LPAREN = 26;
  /** RegularExpression Id. */
  int RPAREN = 27;
  /** RegularExpression Id. */
  int LCOLCH = 28;
  /** RegularExpression Id. */
  int RCOLCH = 29;
  /** RegularExpression Id. */
  int LBRACE = 30;
  /** RegularExpression Id. */
  int RBRACE = 31;
  /** RegularExpression Id. */
  int RBRACE_INTERROG = 32;
  /** RegularExpression Id. */
  int SEMI_COMMA = 33;
  /** RegularExpression Id. */
  int DOT = 34;
  /** RegularExpression Id. */
  int BANG = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int EQUAL = 37;
  /** RegularExpression Id. */
  int AND = 38;
  /** RegularExpression Id. */
  int LESS_THEN = 39;
  /** RegularExpression Id. */
  int BIGGER_THEN = 40;
  /** RegularExpression Id. */
  int PLUS = 41;
  /** RegularExpression Id. */
  int MINUS = 42;
  /** RegularExpression Id. */
  int STAR = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"public\"",
    "\"class\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"return\"",
    "\"extends\"",
    "\"new\"",
    "\"System.out.println\"",
    "\"if\"",
    "\"else\"",
    "\"length\"",
    "\"while\"",
    "\"String\"",
    "\"int\"",
    "\"boolean\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "<DIGIT>",
    "<LETTER>",
    "<INTEGER>",
    "<REAL>",
    "<IDENTIFIER>",
    "<INTEGER_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\")?\"",
    "\";\"",
    "\".\"",
    "\"!\"",
    "\",\"",
    "\"=\"",
    "\"&&\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<token of kind 44>",
    "<token of kind 45>",
    "<token of kind 46>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
